apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: "080525"
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage
      jobs:
        - job
        - job1
    - name: Stage1
      jobs:
        - job2
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  job:
    needs:
      - job1
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
  job2:
    needs:
      - job
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
