apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ChildRWWorkflow
on:
  workflow_call:
jobs:
  hackers-web:
    uses: robkozura/rob-preprod/.cloudbees/workflows/grandchildrwworkflow.yaml
  hackers-auth:
    uses: robkozura/rob-preprod/.cloudbees/workflows/grandchildrwworkflow.yaml
  hackers-api:
    uses: robkozura/rob-preprod/.cloudbees/workflows/grandchildrwworkflow.yaml
