apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ChildRWWorkflow
on:
  workflow_call:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  child:
    needs: build
    uses: robkozura/rob-preprod/.cloudbees/workflows/grandchildrwworkflow.yaml
