apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: circle test
on:
  workflow_dispatch
jobs:
  build:
    needs: build2
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  build2:
    needs: build
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
