apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: july 8 2025 test isStagedWorkflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - deploy-to-Prod
    - name: Stage
      jobs:
        - job
jobs:
  deploy-to-Prod:
    steps:
      - name: Deploy to Prod
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to Prod"
  job:
    needs:
      - deploy-to-Prod
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
