apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Rob Demo 12 19
on:
  push:
    branches:
      - "**112412341234"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world rob"
