apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ThisOneHurts
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
        - job2
        - rob3
    - name: Stage
      jobs:
        - job
        - job5
        - job4
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  job2:
    needs: job1
    uses: robkozura/rob-preprod/.cloudbees/workflows/childrwworkflow.yaml
  rob3:
    needs: job2
    steps:
      - run: echo hello world
        uses: docker://golang:1.20.3-alpine3.17
        name: a
        shell: sh
  job:
    needs: rob3
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  job4:
    steps:
      - run: echo hello world
        uses: docker://golang:1.20.3-alpine3.17
        name: a
        shell: sh
    needs: job5
  job5:
    needs: job
    uses: robkozura/rob-preprod/.cloudbees/workflows/childrwworkflow.yaml
