apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ThisOneHurts
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
        - job2
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  job2:
    needs:
      - job1
    uses: robkozura/rob-preprod/.cloudbees/workflows/childrwworkflow.yaml
