apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ThisOneHurts
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - deploy-to-qa
        - run-tests-qa
        - exit-criteria-qa
    - name: Stage
      jobs:
        - release-manager-approval
        - deploy-to-staging
        - enable-feature-flags-staging
jobs:
  exit-criteria-qa:
    needs: run-tests-qa
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  deploy-to-qa:
    uses: robkozura/rob-preprod/.cloudbees/workflows/childrwworkflow.yaml
  run-tests-qa:
    needs: deploy-to-qa
    steps:
      - run: echo hello world
        uses: docker://golang:1.20.3-alpine3.17
        name: a
        shell: sh
  release-manager-approval:
    needs: exit-criteria-qa
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
  deploy-to-staging:
    needs: release-manager-approval
    uses: robkozura/rob-preprod/.cloudbees/workflows/childrwworkflow.yaml
  enable-feature-flags-staging:
    needs: deploy-to-staging
    steps:
      - run: echo hello world
        uses: docker://golang:1.20.3-alpine3.17
        name: a
        shell: sh
